CREATE TABLE `hotel_vouchers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`bookingRef` varchar(64) NOT NULL DEFAULT '',
	`bookingDate` varchar(32) NOT NULL DEFAULT '',
	`guestName` varchar(255) NOT NULL DEFAULT '',
	`guestList` json DEFAULT ('[]'),
	`numGuests` int NOT NULL DEFAULT 1,
	`hotelName` varchar(255) NOT NULL DEFAULT '',
	`hotelAddress` text,
	`hotelPhone` varchar(64) NOT NULL DEFAULT '',
	`hotelEmail` varchar(255) NOT NULL DEFAULT '',
	`starRating` int NOT NULL DEFAULT 3,
	`hotelImageUrl` text,
	`checkInDate` varchar(32) NOT NULL DEFAULT '',
	`checkInTime` varchar(32) NOT NULL DEFAULT '02:00 PM',
	`checkOutDate` varchar(32) NOT NULL DEFAULT '',
	`checkOutTime` varchar(32) NOT NULL DEFAULT '12:00 PM',
	`numNights` int NOT NULL DEFAULT 1,
	`roomType` varchar(128) NOT NULL DEFAULT '',
	`numRooms` int NOT NULL DEFAULT 1,
	`doubleSharing` int NOT NULL DEFAULT 0,
	`tripleSharing` int NOT NULL DEFAULT 0,
	`childNoBed` int NOT NULL DEFAULT 0,
	`childWithBed` int NOT NULL DEFAULT 0,
	`extraBed` int NOT NULL DEFAULT 0,
	`mealPlan` varchar(64) NOT NULL DEFAULT '',
	`foodPreference` varchar(64) NOT NULL DEFAULT '',
	`inclusions` json DEFAULT ('[]'),
	`specialRequests` text,
	`hotelConfirmationNo` varchar(128) NOT NULL DEFAULT '',
	`agentName` varchar(255) NOT NULL DEFAULT '',
	`agentPhone` varchar(64) NOT NULL DEFAULT '',
	`status` enum('draft','confirmed') NOT NULL DEFAULT 'draft',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `hotel_vouchers_id` PRIMARY KEY(`id`)
);
